### PR TITLE
[185809] Fix to pass dialyzer

### PR DESCRIPTION
**Pull request by aDaichiOta**
https://acsmine.tok.access-company.com/redmine/issues/185809

### CODE REVIEW

**Comment by irisTa56** [comment]
LGTM!

**Comment by ttokit** [comment]
LGTM!

BTW, it’s just curiosity, is it possible to paste the `dialyzer` error that happened in the previous code?

**Comment by aDaichiOta** [comment]
dialyzer warned as follows:
```
web/controller/stress.ex:24: The test 'undefined' == 'prod' can never evaluate to 'true'
web/controller/stress.ex:38: The test 'undefined' == 'prod' can never evaluate to 'true'
```

**Comment by aMasakiTakahashi** [comment]
LGTM!

**Pull request merged**
